[package]
name = "ergotop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "ergotop"
path = "src/main.rs"

[dependencies]
ergotop-core = { path = "../ergotop-core" }
anyhow.workspace = true
clap.workspace = true
crossterm.workspace = true
futures.workspace = true
ratatui.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
webbrowser.workspace = true

[dev-dependencies]
criterion.workspace = true
insta.workspace = true

[[bench]]
name = "frame"
harness = false
