"""One-off: export the Python Ergotop origin tables to assets/builtin-addresses.toml.

Run from the repo root: python scripts/migrate_origins.py
"""
import sys

sys.path.insert(0, ".")
from ergo_mempool_tui.config import MINING_POOLS  # noqa: E402
from ergo_mempool_tui.detection.origins import CONTRACT_ADDRESSES, PLATFORMS  # noqa: E402

EXCHANGES = {"KUCOIN", "NONKYC", "GATE", "MEXC", "HUOBI", "COINEX", "TRADEOGRE", "XEGGEX", "PROBIT"}

lines = ["# Generated by scripts/migrate_origins.py from the Python Ergotop origin tables.", ""]
colors = {}
for addr, key in sorted(CONTRACT_ADDRESSES.items(), key=lambda kv: (kv[1], kv[0])):
    name, color = PLATFORMS[key]
    kind = "Exchange" if key in EXCHANGES else ("MiningPool" if key == "MININGPOOL" else "Service")
    lines += ["[[address]]", f'address = "{addr}"', f'name = "{name}"', f'kind = "{kind}"', ""]
    colors[name] = color
for addr, name in sorted(MINING_POOLS.items(), key=lambda kv: kv[1]):
    lines += ["[[address]]", f'address = "{addr}"', f'name = "{name}"', 'kind = "MiningPool"', ""]
lines.append("[colors]")
for name, color in sorted(colors.items()):
    lines.append(f'"{name}" = "{color}"')
with open("assets/builtin-addresses.toml", "w", newline="\n", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print(len(CONTRACT_ADDRESSES) + len(MINING_POOLS), "addresses written")
